apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-storage
  namespace: seata-demo-at
---
apiVersion: v1
kind: Service
metadata:
  name: api-storage
  namespace: seata-demo-at
  labels:
    app: api-storage
spec:
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app: api-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-storage
  namespace: seata-demo-at
spec:
  selector:
    matchLabels:
      app: api-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: api-storage
    spec:
      serviceAccountName: api-storage
      containers:
      - name: api-storage
        image: registry.example.com/seata/seata-at:sbm-storage-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
