kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-db-pvc
  namespace: seata-demo-at 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api-db
  labels:
    app: api-db
  namespace: seata-demo-at 
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: api-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
  labels:
    app: api-db
  namespace: seata-demo-at 
spec:
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      containers:
        - image: mariadb:10.3.14
          name: api-db
          env:
            - name: TZ
              value: "Asia/Taipei"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: api-db-pvc
