apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-order
  namespace: seata-demo-at
---
apiVersion: v1
kind: Service
metadata:
  name: api-order
  namespace: seata-demo-at
  labels:
    app: api-order
spec:
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app: api-order
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-order
  namespace: seata-demo-at
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-order
    spec:
      serviceAccountName: api-order
      containers:
      - name: api-order
        image: 348053640110.dkr.ecr.us-west-2.amazonaws.com/seata-k8s-at:sbm-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: HSM_URL
            value: "http://api-hsm:8080/api"
          - name: MERCHANT_URL
            value: "http://api-merchant:8080/api"
          - name: MYSQL_HOST
            value: "api-fisc-db.database"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DB
            value: "neptune"
          - name: MYSQL_USER
            value: "fisc"
          - name: MYSQL_PASS
            value: "fisc"
      terminationGracePeriodSeconds: 30

