apiVersion: v1
kind: Service
metadata:
  name: seata 
  namespace: seata-demo-at
  labels:
    app: seata
spec:
  type: ClusterIP
  ports:
  - port: 8091 
    targetPort: 8091 
  selector:
    app: seata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata
  namespace: seata-demo-at
  labels:
    app: seata
spec:
  selector: 
    matchLabels:
      app: seata
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: seata
    spec:
      containers:
      - name: seata
        imagePullPolicy: IfNotPresent
        image: registry.example.com/seata/seata-server:1.1.0
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 8091
