apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-transfer-to
  namespace: seata-demo-tcc
---
apiVersion: v1
kind: Service
metadata:
  name: api-transfer-to
  namespace: seata-demo-tcc
  labels:
    app: api-transfer-to
spec:
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app: api-transfer-to
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-transfer-to
  namespace: seata-demo-tcc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-transfer-to
    spec:
      serviceAccountName: api-transfer-to
      containers:
      - name: api-transfer-to
        image: 348053640110.dkr.ecr.us-west-2.amazonaws.com/seata-k8s-tcc:transfer-to-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 30

